public with sharing class ContactCtrl {
    
    @AuraEnabled
    public static List<Contact> searchContacts(String searchKey){
        searchKey = '%' + searchKey + '%';
        return [SELECT FirstName,LastName,Title,Email
                FROM Contact
                WHERE FirstName LIKE : searchKey
                OR LastName LIKE : searchKey
                WITH SECURITY_ENFORCED
                LIMIT  10];
    }
}